### ISSUE TITLE
brms - missing a compiler?

### ISSUE THREAD

**Issue by ethanknights** [jooh/neuroconda#4] opened 2021-02-11 11:30 UTC
Just to log this - 
With neuroconda R on the CBU setup, I think this error means that a wrong/missing GNU compiler is being pointed to? i.e. `unrecognized command line option ?-std=gnu++14?`

R Package: `brms`
Code from this tutorial: https://github.com/paul-buerkner/brms

```
> library(brms)
Loading required package: Rcpp
Registered S3 method overwritten by 'xts':
  method     from
  as.zoo.xts zoo 
Loading 'brms' package (version 2.10.0). Useful instructions
can be found by typing help('brms'). A more detailed introduction
to the package is available through vignette('brms_overview').
> fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient), 
+             data = epilepsy, family = poisson())
Compiling the C++ model
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! g++: error: unrecognized command line option ?-std=gnu++14?
make: *** [/imaging/local/software/miniconda/envs/neuroconda_2_0/lib/R/etc/Makeconf:175: file437b1d17f5e1.o] Error 1
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command '/imaging/local/software/miniconda/envs/neuroconda_2_0/lib/R/bin/R CMD SHLIB file437b1d17f5e1.cpp 2> file437b1d17f5e1.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection
```

**Comment by jooh** [comment] 2021-02-11 13:00
I'm going to close this here because the problem is almost certainly CBU configuration rather than anything to do with Neuroconda itself. We can discuss further in this issue on the MRC CBU fork of Neuroconda, where all CBU-specific stuff will eventually live:

https://github.com/MRC-CBU/neuroconda/issues/1

**Closed as completed by jooh** 2021-02-11 13:00 UTC
